---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Jace Borcherding"
pagetitle: "L01 Jace Borcherding"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link


[Jace's Repo Link](https://github.com/stat301-3-2026-spring/l01-review-jaceborch-1)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

Define Problem (classification/regression, target variable)

Collect Data and EDA

Split Data (training/testing)

Recipe Creation (Based on EDA)

Resampling set up

Choose Model(s)

Train model

Tune hyperparameters

Train and evaluate final model

:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

Supervised learning has a specific target output, whereas unsupervised learning does not have a target output, and instead aims to discover hidden patterns or structure in the data.

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

These models focus on describing patterns or relationships in the data and do not necessarily make predictions.

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

These models focus on relationships between variables and aim to determine whether a variable has an impact on an outcome.

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

These models are used to predict future or unseen outcomes.

:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

A mechanistic model uses known/assumed structures to explain new outcomes.

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

An empirically driven model is based on observed data, identifying patterns directly from it with minimal assumptions.

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models are often parametric because they are built from equations with a fixed structure, but not always. Empirically driven models are often nonparametric because they rely on data to determine structure. Neither are strict relationships however. The difference is that mechanistic vs empirical is where the model comes from, while parametric vs nonparametric is how rigid of flexible the form is.

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

Mechanistic models because they are built from known/assumed rules or equations so the model is tied to real-world behavior.



:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

Generally, mechanistic models are less flexible as they are built from fixed structures, whereas empirically driven models learn patterns straight from the data and can adapt to fit complex relationships.
:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models typically have higher bias, but lower variance, so they may underfit. Empirical models have lower bias, but more variance, so they are more flexible, so could potentially overfit.

:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

A regression problem has the goal of predicting a continuous numeric value, whereas a classification problem has the goal of predicting a category for the target variable.
:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

It prevents imbalance in splits especially when the original data is imbalanced. It helps so that each part of the split does not under or over represent a certain class in the data.

:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

This type of cross validation splits the data into v folds, and the model is trained v times, holding out on fold for validation. RMSE is computed on the held out fold. We use this process because it is more reliable test of performance than a single split. The repeats esnure the estimate is not overly dependent on one specific fold.
:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

Bootstrap procedures naturally provide an estimate of RMSE values, which makes it easier to quantify uncertainty. It would also be better for imbalanced and small datasets, because in these instances v fold CV can produce unstable folds.

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

Process of selecting best hyperparameter value within a specified range. We use it to find the best hyperparameters to generalize to new data.

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

RMSE, MAE

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

Accuracy, ROC AUC

:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

Inferential, because it is looking to determine the relationship between a specific variable’s impact on customer churn.

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution


Prediction, it is trying to predict the odds that a customer will churn in the next month.

:::

